### ISSUE TITLE
Cannot run sakuli-go-wrapper on macOs

### ISSUE THREAD

**Issue by tnobody** [ConSol/sakuli-go-wrapper#4]
Tried to run the go-wrapper executable on Mac (macOS Sierra V 10.12.6).

Executing sakuli works fine and outputs the "help-message". 

But running `sakuli-go-wrapper run .` outputs the following:
```
panic: Can not detect operatingsystem. Supported are: Windows, Linux
goroutine 1 [running]:
github.com/ConSol/sakuli-go-wrapper/helper.GenClassPath(0xc420041be8, 0x2, 0x2, 0xc42000e3f0, 0x2e)
/Users/timkeiner/go/src/github.com/ConSol/sakuli-go-wrapper/helper/OS.go:29 +0x64
github.com/ConSol/sakuli-go-wrapper/execute.RunSakuli(0x10e33fd, 0x4, 0xc42000e360, 0x2c, 0x0, 0x0, 0x0, 0x1178398, 0x0, 0x0, ...)
/Users/timkeiner/go/src/github.com/ConSol/sakuli-go-wrapper/execute/Sakuli.go:13 +0x19d
main.main()
/Users/timkeiner/go/src/github.com/ConSol/sakuli-go-wrapper/main.go:152 +0xcd3
```
Building on mac also works fine :)

**Comment by toschneck** [comment]
@tnobody any news on this?
